# Generated by Django 4.2.2 on 2023-07-02 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscription_type',
            field=models.CharField(choices=[('streamer', 'Streamer'), ('viewer', 'Viewer')], max_length=200),
        ),
    ]
