# Generated by Django 4.2.2 on 2023-07-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='is_streaming',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stream',
            name='stream_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
